# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
print(*s.split())

Hi there Sam!


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print("The diameter of {planet} is {diameter} kilometers".format(planet="Earth", diameter=12742))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
p=d['k1'][3]
n=p['tricky'][3]
print(n['target'][3])


hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
array=np.zeros(10)
print(array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array1=np.ones(10)*5
print(array1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
l=[]
for i in range(20,35):
  if i%2==0:
    l.append(i)
print(l)

[20, 22, 24, 26, 28, 30, 32, 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
m=[]
i=0
j=0
while i<8:
  j=0
  p=[]
  while j<3:
    p.append(i)
    i+=1
    j+=1
  m.append(p)
print(m)


[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b),axis=0 ))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
data = [10,20,30]
df = pd.DataFrame(data, columns=['Numbers'])
print(df)

   Numbers
0       10
1       20
2       30


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import datetime
test_date = datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")
K = 41


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
df = pd.DataFrame(lists, columns = ['SI','Name','number'])
print(df )

   SI Name  number
0   1  aaa      22
1   2  bbb      25
2   3  ccc      24
